### PR TITLE
MAP and SPAT json validation

### PR DESCRIPTION
**Pull request by iyourshaw**
Add JSON validation for MAP and SPAT messages.

Reorganized and updated the JSON schemas for MAP and SPAT messages to check the JSON messages generated by the ODE for conformance with the J2735 specification and recommendations in the Connected Intersections Implementation Guide CTI 4501 v01.00 document.  MAP and SPAT elements marked as mandatory in the latter document are required in the new JSON schemas.  

The MAP JSON schema includes validations for the items currently available in the tests data, but some of the node level items that aren't present in the test data are incomplete.  In particular NodeListXY/ComputedLane and properties of NodeAttributeSetXY other than dElevation and dWidth are stubbed out to be filled in later.

JSON validation is performed using the [networknt json-schema-validator](https://github.com/networknt/json-schema-validator) library.

Validation errors are currently only written to the log.

Also added Sonar integration with the Jacoco test coverage tool.

### CODE REVIEW

**Comment by drewjj** [comment]
Looks like the CI is failing to connect with the Sonar project. I recall the connection working in the past, we would just get 0% coverage.

**Comment by iyourshaw** [comment]
Probably permissions.  Do I have "Execute Analysis" permission in Sonar Cloud?

**Comment by drewjj** [comment]
> Probably permissions. Do I have "Execute Analysis" permission in Sonar Cloud?

I couldn't say, I don't have access to it.

**Comment by drewjj** [comment]
Maybe lets merge this into a feature branch and we can make another pr internally to this repository. You should have permissions to this repository now. I think the additions look great though.

**Pull request closed without merging**
